version: '3.1'

services:
  jaegertracing:
    image: jaegertracing/all-in-one:1.7
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    hostname: jaegertracing
  service1:
    image: gin-opentracing-example
    build:
      context: .
      dockerfile: Dockerfile
    hostname: service1
    container_name: service1
    ports:
      - "3100:3100"
    command: gin-opentracing service1
  service2:
    image: gin-opentracing-example
    container_name: service2
    hostname: service2
    ports:
      - "3200:3200"
    command: gin-opentracing service2